const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Browser,
		C3.Plugins.Text,
		C3.Plugins.Button,
		C3.Plugins.Touch,
		C3.Plugins.Mouse,
		C3.Plugins.Sprite,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.JavaScriptInEvents.EventSheet1_Event1_Act1,
		C3.JavaScriptInEvents.EventSheet1_Event2,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Audio.Acts.Play,
		C3.JavaScriptInEvents.EventSheet1_Event3_Act2,
		C3.JavaScriptInEvents.EventSheet1_Event4,
		C3.JavaScriptInEvents.EventSheet1_Event5,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.JavaScriptInEvents.EventSheet1_Event8_Act2,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Browser.Acts.GoToURL
	];
};
self.C3_JsPropNameTable = [
	{Browser: 0},
	{txtWalletAddress: 0},
	{Button: 0},
	{Touch: 0},
	{Mouse: 0},
	{Connect: 0},
	{txtBNB: 0},
	{txtInfinity: 0},
	{Contrato: 0},
	{Sprite: 0},
	{txtConectar: 0},
	{Text2: 0},
	{Sprite2: 0},
	{Text3: 0},
	{Text4: 0},
	{txtOutro: 0},
	{PooCOin: 0},
	{Pan: 0},
	{Text: 0},
	{Text6: 0},
	{Audio: 0},
	{Outro: 0},
	{walletAddress: 0},
	{walletBNB: 0},
	{walletInfinity: 0}
];

self.InstanceType = {
	Browser: class extends self.IInstance {},
	txtWalletAddress: class extends self.ITextInstance {},
	Button: class extends self.IButtonInstance {},
	Touch: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Connect: class extends self.ISpriteInstance {},
	txtBNB: class extends self.ITextInstance {},
	txtInfinity: class extends self.ITextInstance {},
	Contrato: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	txtConectar: class extends self.ITextInstance {},
	Text2: class extends self.ITextInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Text3: class extends self.ITextInstance {},
	Text4: class extends self.ITextInstance {},
	txtOutro: class extends self.ITextInstance {},
	PooCOin: class extends self.ISpriteInstance {},
	Pan: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Text6: class extends self.ITextInstance {},
	Audio: class extends self.IInstance {},
	Outro: class extends self.ISpriteInstance {}
}